# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

#pool:
  #vmImage: ubuntu-latest
  #name: 'Default'

stages:
 - stage: 'initial_stage'
   jobs:
    - job: 'initial_stage'
      pool:
        name: 'Other'
      steps:
        - script: echo "Initial_stage"

 - stage: 'Scan'
   dependsOn: initial_stage
   condition: succeeded()
   jobs:
    - job: 'Scan'
      pool:
        name: 'Default'
      steps:
      - task: Application security testing@2023
        inputs:
          projectName: 'Azure-test'
          enableProxy: false
          enableSastScan: true
          CheckmarxService: 'Checkmarx Onprem'
          fullTeamName: 'CxServer'
          incScan: false
          enableDependencyScan: true
          dependencyServerURL: 'Checkmars SCA'
          scaTeam: '/CxServer'